### ISSUE TITLE
panic trying to parse URL during ContainerCreate

### ISSUE THREAD

**Issue by encryptio** [ncw/swift#33] opened 2015-02-13 22:11 UTC
I'm getting this sometimes on ContainerCreate:

    panic: runtime error: invalid memory address or nil pointer dereference
    [signal 0xb code=0x1 addr=0x0 pc=0x566047]

    goroutine 50 [running]:
    runtime.panic(0x74cf80, 0x96f3d3)
            /usr/lib/golang/src/pkg/runtime/panic.c:279 +0xf5
    net/url.(*URL).ResolveReference(0x0, 0xc208029650, 0xc208029650)
            /usr/lib/golang/src/pkg/net/url/url.go:648 +0x207
    net/url.(*URL).Parse(0x0, 0x0, 0x0, 0xc20813ab70, 0x0, 0x0)
            /usr/lib/golang/src/pkg/net/url/url.go:636 +0x8d
    github.com/ncw/swift.(*Connection).Call(0xc20811c000, 0x0, 0x0, 0xc208137b0c, 0x4, 0x0, 0x0, 0x78feb0, 0x3, 0x0, ...)
            /.../src/github.com/ncw/swift/swift.go:437 +0x1d0
    github.com/ncw/swift.(*Connection).storage(0xc20811c000, 0xc208137b0c, 0x4, 0x0, 0x0, 0x78feb0, 0x3, 0x0, 0x0, 0xc208022ae0, ...)
            /.../src/github.com/ncw/swift/swift.go:521 +0x142
    github.com/ncw/swift.(*Connection).ContainerCreate(0xc20811c000, 0xc208137b0c, 0x4, 0x0, 0x0, 0x0)
            /.../src/github.com/ncw/swift/swift.go:975 +0xbd
    $MYPROGRAM/resource.swiftResource.Upload(0xc20811c000, 0xc208137b0c, 0x4, 0xc208137b11, 0x1c, 0xc208043e00, 0x3a, 0xc2080caa20, 0x0, 0x0)
            /.../src/$MYPROGRAM/resource/swift.go:130 +0xf4
    $MYPROGRAM/resource.(*swiftResource).Upload(0xc208022f60, 0xc208043e00, 0x3a, 0xc2080caa20, 0x0, 0x0)
    ...unrelated stack frames...

From the rest of the stack traces, no other goroutines are running in any code in the swift library.

Using go 1.3.3 with OpenStack Swift Grizzly (and OpenStack Keystone Grizzly for auth), ncw/swift as of 71da36c561d45ba5420b99262689f91f2d9b8db4.

Isn't the `url` package being shadowed by the `url` variable declared on line 436? This seems to universally panic when targetUrl does not contain a scheme. That said, I don't know why it wouldn't contain a scheme in the first place.

Unlike #26, I have no other interesting log lines around this panic.

The memcached for Keystone was not up during the time that this failed; it was probably not returning useful data.

**Comment by encryptio** [comment] 2015-02-13 22:20
To be clear, I don't think the issue is in ContainerCreate; it just happens that the code always calls that function first.

**Comment by ncw** [comment] 2015-02-14 14:50
Thanks for reporting this.

I think the problem is as you stated that the url package is shadowed by the url variable.

Most of the time it doesn't matter, however occasionally your setup is sending a non absolute URL which will cause `ResolveReference` to try to read through the `nil` url variable and cause the panic.

I've pushed what I think is the fix to the issue-33 branch.

Can you have a go?  I expect you will see a more sensible error at that point to do with malformed URLs rather than a panic.

Thanks

Nick

**Comment by encryptio** [comment] 2015-02-17 19:54
Looks good!

Now I get this error instead when I run my reproducer:

    Get /dummycontainer/dummyobject: unsupported protocol scheme ""

Which is somewhat misleading, but significantly better than a panic.

Upon the next successful authentication request, it goes back to working as expected, without recreating the Connection object.

**Comment by ncw** [comment] 2015-02-19 17:17
Thanks for the bug report; I've merged the fix to master.

**Closed** 2015-02-19 17:16 UTC
